/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'James' at '9/15/17 5:01 AM' with Gradle 2.13
 *
 * @author James, @date 9/15/17 5:01 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
